name: JS

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22.x
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check-format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22.x
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22.x
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check-types

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22.x
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright Deps
        run: pnpm exec playwright install --with-deps
      - run: pnpm run test
